### ISSUE TITLE
[优化]驼峰属性名不支持改成连字符形式

### ISSUE THREAD

**Issue by HyokaChen** [rashagu/semi-design-vue#13]
![image](https://github.com/rashagu/semi-design-vue/assets/13757028/19fa1656-55d3-45ab-aa06-ecc281d2e569)
vscode提示的是连字符形式，但是如果这么写nolabel就不会生效。必须改成如下：
![image](https://github.com/rashagu/semi-design-vue/assets/13757028/02abc350-57d6-4563-808a-bce35f4f036d)
然后就能够去掉label了。
![image](https://github.com/rashagu/semi-design-vue/assets/13757028/eeaff0b3-0e38-43ab-8ebc-a50225f33c0c)

不知道算不算bug或者可以优化的。目前使用上倒没有问题，只是这样vs的提示就无效了。

**Comment by rashagu** [comment]
![微信图片_20240702135406](https://github.com/rashagu/semi-design-vue/assets/80970516/cade0a45-2388-4e93-95ed-008b69db198d)
之前是attrs接收，驼峰没有自动转换，现在改成props就可以了
