### ISSUE TITLE
Chat 组件设置滚动高度后报错

### ISSUE THREAD

**Issue by linyupark** [rashagu/semi-design-vue#18]
复现方式：
设置chat 高度，并上下滚动

报错主要信息：
persist is not a function

AI的分析：
根据您提供的错误信息,这个问题似乎是由于在Vue 3环境中使用了React风格的事件处理方法造成的。具体来说,e16.persist() 是React中的一个方法,用于保留合成事件,但在Vue中并不存在这个方法。

**Comment by rashagu** [comment]
已更新
