### ISSUE TITLE
Chat组件Assitant消息底部Action Button没有控制是否显示以及显示哪些action的设置

### ISSUE THREAD

**Issue by jeanslin** [rashagu/semi-design-vue#20]
Chat组件没有Action Button配置
无法灵活控制是否要显示action button以及显示哪些action
希望有相关的配置来控制这一块的功能

![image](https://github.com/user-attachments/assets/705353af-5799-40e4-8621-fb9ed5e4a7c8)

**Comment by rashagu** [comment]
通过 renderChatBoxAction 自定义渲染操作区 [具体参考文档](https://www.kousum.asia/zh-CN/plus/chat/#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B8%B2%E6%9F%93%E4%BC%9A%E8%AF%9D%E6%A1%86)

``` tsx
    <Chat
      chatBoxRenderConfig={{
        renderChatBoxAction: customRenderAction
      }}
      style={commonOuterStyle}
      chats={message.value}
      onChatsChange={onChatsChange}
      onMessageSend={onMessageSend}
      roleConfig={roleInfo}
      uploadProps={uploadProps}
    />
```
