### ISSUE TITLE
关于 Input 组件前缀问题

### ISSUE THREAD

**Issue by luzilong2005** [rashagu/semi-design-vue#22]
希望当 prefix、suffix 传入自定义的图标组件时，能够带上左右间隔

**Comment by rashagu** [comment]
官方是这么设计的：当 prefix、suffix 传入的内容为文本或者 Semi Icon 时，会自动带上左右间隔，若为自定义 Node，则左右间隔为 0。

既然是自定义组件，边距自行加上就是了。这也是保证自定义组件能够自由发挥，如果加上的话可能有些人的自定义组件他不想要边距。

**Comment by luzilong2005** [comment]
有考虑为Input组件加上控制间距的属性吗，需要时就开启

**Comment by luzilong2005** [comment]
有考虑为Input组件加上控制间距的属性吗，需要时就开启。

**Comment by luzilong2005** [comment]
> 官方是这么设计的：当 prefix、suffix 传入的内容为文本或者 Semi Icon 时，会自动带上左右间隔，若为自定义 Node，则左右间隔为 0。
> 
> 既然是自定义组件，边距自行加上就是了。这也是保证自定义组件能够自由发挥，如果加上的话可能有些人的自定义组件他不想要边距。

有考虑为Input组件加上控制间距的属性吗，需要时就开启

**Comment by rashagu** [comment]
暂不考虑，目前同步官方组件
