### ISSUE TITLE
Notification组件与官方文档不一致，用不了，方法好像没暴露出来

### ISSUE THREAD

**Issue by mark980828** [rashagu/semi-design-vue#7]
重现：https://stackblitz.com/edit/vitejs-vite-x3uukw?file=src%2FApp.vue
Notification.success({
    title: 'Hi, Bytedance',
    content: 'Hi, Bytedance dance dance',
    duration: 3,
    theme: 'light',
 });

**Comment by rashagu** [comment]
已更新至 v0.8.5
